version: '3.4'

services:
    db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=admin
            - POSTGRES_USER=admin
        ports:
            - "5432:5432"
        volumes:
            - ${APPDATA}/custom/mount:/var/lib/postgresql/data
        networks:
            - todo_nets

    todo-server:
        image: ${DOCKER_REGISTRY-}todoserver
        build:
            context: .
            dockerfile: Server/Dockerfile
        environment:
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_ENVIRONMENT=Development
            - Database:Server=db
            - Database:Name=ToDo
            - Database:User=admin
            - Database:Password=admin
        ports:
            - "1555:80"
            - "15555:443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        depends_on:
            - db
        networks:
            - todo_nets

    todo.client:
        image: ${DOCKER_REGISTRY-}todoclient
        build:
          context: .
          dockerfile: Client/Dockerfile
        environment:
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_ENVIRONMENT=Development
            - ServerUrl=http://mahmud.api.20.219.235.7.nip.io/api/
        ports:
            - "1666:80"
            - "16666:443"
        depends_on:
            - todo-server
        networks:
            - todo_nets

networks:
  todo_nets:
    driver: bridge

volumes:
  esdata01:
    driver: local
  kibanadata:
    driver: local


