version: '3.4'

services:
  todo.server:
    image: ${DOCKER_REGISTRY-}todoserver
    build:
      context: .
      dockerfile: Server/Dockerfile
  todo.webui:
    image: ${DOCKER_REGISTRY-}todowebui
    build:
      context: .
      dockerfile: WebUI/Dockerfile

