apiVersion: v1
kind: Namespace
metadata:
  name: todo-dev
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-configmap
  namespace: todo-dev
data:
  server_url: http://api.localdev.me:8080/api/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: todo-dev
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: todo-client
          image: mahmudsharipov/todoclient:1.1
          resources:
            limits:
              memory: "3Gi"
              cpu: "1"
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: ASPNETCORE_URLS
              value: https://+:443;http://+:80
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: Server
              valueFrom:
                configMapKeyRef:
                  name: client-configmap
                  key: server_url
---
apiVersion: v1
kind: Service
metadata:
  name: todo-client-service
  namespace: todo-dev
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 1666
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-server-ingress
  namespace: todo-dev
spec:
  ingressClassName: nginx
  rules:
    - host: client.localdev.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-client-service
                port:
                  number: 1666