version: '3.4'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
    volumes:
      - ${APPDATA}/custom/mount:/var/lib/postgresql/data
    networks:
      - todo_nets

  todo-api:
    image: ${DOCKER_REGISTRY-}todoapi
    build:
      context: .
      dockerfile: API/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - Database__Server=db
      - Database__Name=ToDo
      - Database__User=admin
      - Database__Password=admin
    ports:
      - "1555:80"
      - "15555:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - db
    networks:
      - todo_nets

  todo-client:
    image: ${DOCKER_REGISTRY-}todowebserver
    build:
      context: .
      dockerfile: Web.Server/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - TodoApiUrl=http://todo-api/api/
    ports:
      - "1666:80"
      - "16666:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    depends_on:
      - todo-api
    networks:
      - todo_nets

networks:
  todo_nets:
    driver: bridge

volumes:
  esdata01:
    driver: local
  kibanadata:
    driver: local

