name: Build Docker image
on:
  workflow_dispatch:
    inputs:
      name:
        description: Who to greet
        default: 1.0.0
        required: true
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker image
        run: docker build -f "..\..\src\Web.Server\Dockerfile" --force-rm -t todoclient:${{ github.event.inputs.environment }} --target final "..\..\src"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image to Docker Hub
        run: docker push todoclient:${{ github.event.inputs.environment }}
